# sampley exemplar: Stage 3
Before going through this exemplar, please consult the Introduction to sampley exemplars (```intro.ipynb```).
<br>This exemplar illustrates the classes that can be made in Stage 3, their class methods, their attributes, and their methods.

## Setup

### Import the package

In [1]:
from sampley import *

### Set the import folder
To run this exemplar, download the mock data files, put them in a folder, and set the path to the folder below.

In [2]:
import_folder = './import/'

### Set the export folder
To run this exemplar, make a folder to save the samples in and set the path to the folder below.

In [3]:
export_folder = './export/'

### Make DataPoints, Sections, and delimiters (Stages 1 and 2)
Before making any objects in Stage 3, we, of course, have to conduct Stages 1 and 2. For the sake of this exemplar, we make one ```Sections``` and one ```DataPoints``` object below that are then used to make all the subsequent delimiters. See the Stage 1 and 2 exemplars and the User Manual for more details on Stages 1 and 2.

In [4]:
u_sightings = DataPoints.from_file(
    filepath=import_folder+'sightings.gpkg',
    crs_working='EPSG:32619',
    datetime_col='datetime',
    tz_import='UTC-05:00'
)

Success: file opened.
Success: reprojected to CRS "EPSG:32619"
Success: column "datetime" reformatted to datetimes.
Success: timezone of column "datetime" set to "UTC-05:00".
Success: datapoint IDs generated.

In [5]:
u_sections = Sections.from_file(
    filepath=import_folder+'sections.gpkg',
    crs_working='EPSG:32619',
    datetime_col='datetime',
    tz_import='UTC-05:00'
)

Success: file opened.
Success: reprojected to CRS "EPSG:32619"
Success: column "datetime" reformatted to datetimes.
Success: timezone of column "datetime" set to "UTC-05:00".
Success: section IDs generated.

In [6]:
u_periods = Periods.delimit(
    extent=u_sections,
    unit='day',
    num=8)

In [7]:
u_cells = Cells.delimit(
    extent=u_sections,
    var='hexagonal',
    side=5000,
    buffer=2000)

In [8]:
u_segments = Segments.delimit(
    sections=u_sections,
    var='simple',
    target=10000,
    rand=True)

In [9]:
u_presences = Presences.delimit(
    datapoints=u_sightings,
    presence_col='individuals')

In [10]:
u_presencezones = PresenceZones.delimit(
    sections=u_sections,
    presences=u_presences,
    sp_threshold=10000,
    tm_threshold=5,
    tm_unit='day',
)

In [11]:
u_absences = Absences.delimit(
    sections=u_sections,
    presencezones=u_presencezones,
    var='along',
    target=20,
    dfls=None)

Target: 20 | Attempts: 28 | Successes: 20

## Samples - grid approach

### Make a ```Samples``` object via the grid approach...
If using the grid approach, we can make a ```Samples``` object from a ```DataPoints``` object with the ```Samples.grid()``` class method.
<br>We can also make a ```Samples``` object with measures of survey effort from a ```Sections``` object with the ```Samples.grid_se()``` class method.
<br>Additionally, we can merge multiple ```Samples``` objects into a single new ```Samples``` object with the ```Samples.merge()``` class method

#### ...from a ```DataPoints``` object

In [12]:
u_samples_sightings = Samples.grid(
    datapoints=u_sightings,
    cells=u_cells,
    periods=u_periods,
    cols={'individuals': 'sum'})

#### ...from a ```Sections``` object

In [13]:
u_samples_effort = Samples.grid_se(
    sections=u_sections,
    cells=u_cells,
    periods=u_periods,
    esw=None)

#### ...by merging multiple ```Samples``` objects

In [14]:
u_samples = Samples.merge(
    sightings=u_samples_sightings,
    effort=u_samples_effort)

Note: samples generated with the grid approach

### Access a ```Samples``` object's attributes
A ```Samples``` object, regardless of how it was made, will have three attributes (```name```, ```parameters```, and ```samples```) that we can access as follows.

In [15]:
u_samples.name

'samples-sightings+effort-x-cells-h5000m-x-periods-8d'

In [16]:
u_samples.parameters

{'name': 'samples-sightings+effort-x-cells-h5000m-x-periods-8d',
 'names': 'samples-datapoints-sightings-x-cells-h5000m-x-periods-8d+samples-sections-sections-x-cells-h5000m-x-periods-8d',
 'approach': 'grid',
 'resampled': 'datapoints; effort',
 'datapoints_name': 'datapoints-sightings; nan',
 'datapoints_filepath': './import/sightings.gpkg; nan',
 'datapoints_crs': 'EPSG:32619; nan',
 'datapoints_tz': 'UTC-05:00; nan',
 'datapoints_data_cols': 'individuals, season; nan',
 'cells_name': 'cells-h5000m',
 'cells_crs': 'EPSG:32619',
 'cells_extent': '493765.49253164633, 4689798.086839909, 671300.7003074563, 4759798.086839909',
 'cells_extent_source': 'Sections - sections-sections',
 'cells_var': 'hexagonal',
 'cells_side': '5000',
 'cells_unit': 'metre',
 'cells_buffer': '2000',
 'periods_name': 'periods-8d',
 'periods_tz': 'UTC-05:00',
 'periods_extent': '2019-01-25-2019-03-05',
 'periods_extent_source': 'Sections - sections-sections',
 'periods_number': '8',
 'periods_unit': 'day',
 'cols': "{'individuals': 'sum'}; nan",
 'sections_name': 'nan; sections-sections',
 'sections_filepath': 'nan; ./import/sections.gpkg',
 'sections_crs': 'nan; EPSG:32619',
 'sections_tz': 'nan; UTC-05:00',
 'effort_esw': 'nan; None',
 'effort_euc-geo': 'nan; euclidean'}

In [17]:
u_samples.samples

,cell_id,polygon,centroid,period_id,date_beg,date_mid,date_end,individuals,se_length
0,c013-h5000m,"POLYGON ((602018.668 4699798.087, 606348.795 4...",POINT (602018.668 4694798.087),p2019-02-26-8d,2019-02-26 00:00:00-05:00,2019-03-02 00:00:00-05:00,2019-03-05 00:00:00-05:00,NaN,4000.286022
1,c014-h5000m,"POLYGON ((610678.922 4699798.087, 615009.049 4...",POINT (610678.922 4694798.087),p2019-02-26-8d,2019-02-26 00:00:00-05:00,2019-03-02 00:00:00-05:00,2019-03-05 00:00:00-05:00,4.0,8662.075856
2,c015-h5000m,"POLYGON ((619339.176 4699798.087, 623669.303 4...",POINT (619339.176 4694798.087),p2019-02-26-8d,2019-02-26 00:00:00-05:00,2019-03-02 00:00:00-05:00,2019-03-05 00:00:00-05:00,2.0,8661.517653
3,c016-h5000m,"POLYGON ((627999.43 4699798.087, 632329.557 46...",POINT (627999.43 4694798.087),p2019-02-26-8d,2019-02-26 00:00:00-05:00,2019-03-02 00:00:00-05:00,2019-03-05 00:00:00-05:00,NaN,8577.463371
4,c017-h5000m,"POLYGON ((636659.684 4699798.087, 640989.811 4...",POINT (636659.684 4694798.087),p2019-02-26-8d,2019-02-26 00:00:00-05:00,2019-03-02 00:00:00-05:00,2019-03-05 00:00:00-05:00,NaN,8234.234607
...,...,...,...,...,...,...,...,...,...
105,c147-h5000m,"POLYGON ((554387.271 4752298.087, 558717.398 4...",POINT (554387.271 4747298.087),p2019-01-25-8d,2019-01-25 00:00:00-05:00,2019-01-29 00:00:00-05:00,2019-02-01 00:00:00-05:00,2.0,1543.406690
106,c148-h5000m,"POLYGON ((563047.525 4752298.087, 567377.652 4...",POINT (563047.525 4747298.087),p2019-01-25-8d,2019-01-25 00:00:00-05:00,2019-01-29 00:00:00-05:00,2019-02-01 00:00:00-05:00,NaN,1704.820261
107,c149-h5000m,"POLYGON ((571707.779 4752298.087, 576037.906 4...",POINT (571707.779 4747298.087),p2019-01-25-8d,2019-01-25 00:00:00-05:00,2019-01-29 00:00:00-05:00,2019-02-01 00:00:00-05:00,NaN,1869.663454
108,c150-h5000m,"POLYGON ((580368.033 4752298.087, 584698.16 47...",POINT (580368.033 4747298.087),p2019-01-25-8d,2019-01-25 00:00:00-05:00,2019-01-29 00:00:00-05:00,2019-02-01 00:00:00-05:00,NaN,724.066435
109,c159-h5000m,"POLYGON ((658310.319 4752298.087, 662640.446 4...",POINT (658310.319 4747298.087),p2019-02-26-8d,2019-02-26 00:00:00-05:00,2019-03-02 00:00:00-05:00,2019-03-05 00:00:00-05:00,NaN,7977.949999

### Modify a ```Samples``` object
Before we save our ```Samples``` object, there are a few things that we might want to modify.

#### Reproject
We can reproject our ```Samples``` object to a CRS of our choosing with the ```Samples.reproject()``` method which takes a single argument: the target CRS.
<br>In our example below, we reproject our ```Samples``` object to EPSG:4326 and then print it to see that the ```polygon``` and ```centroid``` columns are now in lat-lon coordinates.

In [18]:
u_samples.reproject(crs_target='EPSG:4326')
u_samples.samples

Success: additional geometry column "centroid" reprojected to CRS "EPSG:4326"
Success: reprojected to CRS "EPSG:4326"

,cell_id,polygon,centroid,period_id,date_beg,date_mid,date_end,individuals,se_length
0,c013-h5000m,"POLYGON ((-67.7595 42.4438, -67.70733 42.42071...",POINT (-67.76039 42.39878),p2019-02-26-8d,2019-02-26 00:00:00-05:00,2019-03-02 00:00:00-05:00,2019-03-05 00:00:00-05:00,NaN,4000.286022
1,c014-h5000m,"POLYGON ((-67.65423 42.44261, -67.60209 42.419...",POINT (-67.65519 42.39759),p2019-02-26-8d,2019-02-26 00:00:00-05:00,2019-03-02 00:00:00-05:00,2019-03-05 00:00:00-05:00,4.0,8662.075856
2,c015-h5000m,"POLYGON ((-67.54896 42.44133, -67.49686 42.418...",POINT (-67.54999 42.39631),p2019-02-26-8d,2019-02-26 00:00:00-05:00,2019-03-02 00:00:00-05:00,2019-03-05 00:00:00-05:00,2.0,8661.517653
3,c016-h5000m,"POLYGON ((-67.44369 42.43995, -67.39164 42.416...",POINT (-67.44481 42.39493),p2019-02-26-8d,2019-02-26 00:00:00-05:00,2019-03-02 00:00:00-05:00,2019-03-05 00:00:00-05:00,NaN,8577.463371
4,c017-h5000m,"POLYGON ((-67.33844 42.43847, -67.28643 42.415...",POINT (-67.33963 42.39346),p2019-02-26-8d,2019-02-26 00:00:00-05:00,2019-03-02 00:00:00-05:00,2019-03-05 00:00:00-05:00,NaN,8234.234607
...,...,...,...,...,...,...,...,...,...
105,c147-h5000m,"POLYGON ((-68.33359 42.92137, -68.2808 42.8985...",POINT (-68.33407 42.87634),p2019-01-25-8d,2019-01-25 00:00:00-05:00,2019-01-29 00:00:00-05:00,2019-02-01 00:00:00-05:00,2.0,1543.406690
106,c148-h5000m,"POLYGON ((-68.22748 42.9207, -68.17473 42.8978...",POINT (-68.22805 42.87568),p2019-01-25-8d,2019-01-25 00:00:00-05:00,2019-01-29 00:00:00-05:00,2019-02-01 00:00:00-05:00,NaN,1704.820261
107,c149-h5000m,"POLYGON ((-68.12138 42.91993, -68.06867 42.897...",POINT (-68.12202 42.87491),p2019-01-25-8d,2019-01-25 00:00:00-05:00,2019-01-29 00:00:00-05:00,2019-02-01 00:00:00-05:00,NaN,1869.663454
108,c150-h5000m,"POLYGON ((-68.01529 42.91907, -67.96262 42.896...",POINT (-68.016 42.87405),p2019-01-25-8d,2019-01-25 00:00:00-05:00,2019-01-29 00:00:00-05:00,2019-02-01 00:00:00-05:00,NaN,724.066435
109,c159-h5000m,"POLYGON ((-67.06069 42.90688, -67.00841 42.883...",POINT (-67.0621 42.86188),p2019-02-26-8d,2019-02-26 00:00:00-05:00,2019-03-02 00:00:00-05:00,2019-03-05 00:00:00-05:00,NaN,7977.949999

#### Extract coordinates
The coordinates of the ```centroid``` column are now in lat-lon but they are still in a ```shapely.geometry``` which may complicate things later, if we want to, for example, get values for environmental variables from a satellite dataset at the coordinates of each centroid. So, we can use the ```Samples.coords()``` method to make two new columns: ```centroid_lat``` and ```centroid_lon```.
<br>We then print the samples to see these new columns.

In [19]:
u_samples.coords()
u_samples.samples

,cell_id,polygon,centroid,centroid_lon,centroid_lat,period_id,date_beg,date_mid,date_end,individuals,se_length
0,c013-h5000m,"POLYGON ((-67.7595 42.4438, -67.70733 42.42071...",POINT (-67.76039 42.39878),-67.760392,42.398780,p2019-02-26-8d,2019-02-26 00:00:00-05:00,2019-03-02 00:00:00-05:00,2019-03-05 00:00:00-05:00,NaN,4000.286022
1,c014-h5000m,"POLYGON ((-67.65423 42.44261, -67.60209 42.419...",POINT (-67.65519 42.39759),-67.655190,42.397594,p2019-02-26-8d,2019-02-26 00:00:00-05:00,2019-03-02 00:00:00-05:00,2019-03-05 00:00:00-05:00,4.0,8662.075856
2,c015-h5000m,"POLYGON ((-67.54896 42.44133, -67.49686 42.418...",POINT (-67.54999 42.39631),-67.549995,42.396312,p2019-02-26-8d,2019-02-26 00:00:00-05:00,2019-03-02 00:00:00-05:00,2019-03-05 00:00:00-05:00,2.0,8661.517653
3,c016-h5000m,"POLYGON ((-67.44369 42.43995, -67.39164 42.416...",POINT (-67.44481 42.39493),-67.444806,42.394933,p2019-02-26-8d,2019-02-26 00:00:00-05:00,2019-03-02 00:00:00-05:00,2019-03-05 00:00:00-05:00,NaN,8577.463371
4,c017-h5000m,"POLYGON ((-67.33844 42.43847, -67.28643 42.415...",POINT (-67.33963 42.39346),-67.339626,42.393457,p2019-02-26-8d,2019-02-26 00:00:00-05:00,2019-03-02 00:00:00-05:00,2019-03-05 00:00:00-05:00,NaN,8234.234607
...,...,...,...,...,...,...,...,...,...,...,...
105,c147-h5000m,"POLYGON ((-68.33359 42.92137, -68.2808 42.8985...",POINT (-68.33407 42.87634),-68.334075,42.876343,p2019-01-25-8d,2019-01-25 00:00:00-05:00,2019-01-29 00:00:00-05:00,2019-02-01 00:00:00-05:00,2.0,1543.406690
106,c148-h5000m,"POLYGON ((-68.22748 42.9207, -68.17473 42.8978...",POINT (-68.22805 42.87568),-68.228046,42.875677,p2019-01-25-8d,2019-01-25 00:00:00-05:00,2019-01-29 00:00:00-05:00,2019-02-01 00:00:00-05:00,NaN,1704.820261
107,c149-h5000m,"POLYGON ((-68.12138 42.91993, -68.06867 42.897...",POINT (-68.12202 42.87491),-68.122022,42.874913,p2019-01-25-8d,2019-01-25 00:00:00-05:00,2019-01-29 00:00:00-05:00,2019-02-01 00:00:00-05:00,NaN,1869.663454
108,c150-h5000m,"POLYGON ((-68.01529 42.91907, -67.96262 42.896...",POINT (-68.016 42.87405),-68.016001,42.874051,p2019-01-25-8d,2019-01-25 00:00:00-05:00,2019-01-29 00:00:00-05:00,2019-02-01 00:00:00-05:00,NaN,724.066435
109,c159-h5000m,"POLYGON ((-67.06069 42.90688, -67.00841 42.883...",POINT (-67.0621 42.86188),-67.062105,42.861876,p2019-02-26-8d,2019-02-26 00:00:00-05:00,2019-03-02 00:00:00-05:00,2019-03-05 00:00:00-05:00,NaN,7977.949999

### Save a ```Samples``` object
```Samples``` objects have an inbuilt ```save``` method to save the samples as a CSV or GPKG. The name of the saved file will be the name of the ```Samples``` object.

In [20]:
print(f'The saved file will be called \'{u_samples.name}.csv\'')
u_samples.save(
    folder=export_folder,
    filetype='gpkg'
)

The saved file will be called 'samples-sightings+effort-x-cells-h5000m-x-periods-8d.csv'

## Samples - segment approach

### Make a ```Samples``` object...
If using the segment approach, we can make a ```Samples``` object from a ```DataPoints``` object with the ```Samples.segment()``` class method.
<br>We can also make a ```Samples``` object with measures of survey effort from a ```Segments``` object with the ```Samples.segment_se()``` class method.
<br>Additionally, we can merge multiple ```Samples``` objects into a single new ```Samples``` object with the ```Samples.merge()``` class method.

#### ...from a ```DataPoints``` object

In [21]:
u_samples_sightings = Samples.segment(
    datapoints=u_sightings,
    segments=u_segments,
    cols={'individuals': 'sum'},
    how='midpoint')

#### ...from a ```Sections``` object

In [22]:
u_samples_effort = Samples.segment_se(
    segments=u_segments,
    esw=2000)

#### ...by merging multiple ```Samples``` objects

In [23]:
u_samples = Samples.merge(
    sightings=u_samples_sightings,
    effort=u_samples_effort)

Note: samples generated with the segment approach

### Access a ```Samples``` object's attributes
A ```Samples``` object, regardless of how it was made, will have three attributes (```name```, ```parameters```, and ```samples```) that we can access as follows.

In [24]:
u_samples.name

'samples-sightings+effort-x-segments-s10000m'

In [25]:
u_samples.parameters

{'name': 'samples-sightings+effort-x-segments-s10000m',
 'names': 'samples-datapoints-sightings-x-segments-s10000m+samples-sections-sections-x-segments-s10000m',
 'approach': 'segment',
 'resampled': 'datapoints; effort',
 'datapoints_name': 'datapoints-sightings; nan',
 'datapoints_filepath': './import/sightings.gpkg; nan',
 'datapoints_crs': 'EPSG:32619; nan',
 'datapoints_tz': 'UTC-05:00; nan',
 'datapoints_data_cols': 'individuals, season; nan',
 'segments_name': 'segments-s10000m',
 'sections_name': 'sections-sections',
 'segments_crs': 'EPSG:32619',
 'segments_var': 'simple',
 'segments_rand': 'True',
 'segments_target': '10000',
 'segments_unit': 'metre',
 'cols': "{'individuals': 'sum'}; nan",
 'effort_esw': 'nan; 2000.0',
 'effort_audf': 'nan; None',
 'effort_euc-geo': 'nan; euclidean'}

In [26]:
u_samples.samples

,segment_id,line,midpoint,date,section_id,dfbsec_beg,dfbsec_end,individuals,se_length,se_area
0,s01-s10000m,"LINESTRING (580092.757 4742883.408, 579997.135...",POINT (575093.311 4742845.962),2019-01-25,s1,0.000000,10000.000000,1.0,10000.0,4.000000e+07
1,s02-s10000m,"LINESTRING (570094.222 4742829.916, 569917.081...",POINT (565094.73 4742799.725),2019-01-25,s1,10000.000000,20000.000000,NaN,10000.0,4.000000e+07
2,s03-s10000m,"LINESTRING (560095.148 4742773.163, 559864.339...",POINT (555095.521 4742749.119),2019-01-25,s1,20000.000000,30000.000000,2.0,10000.0,4.000000e+07
3,s04-s10000m,"LINESTRING (550095.667 4742710.935, 549838.842...",POINT (545095.787 4742676.383),2019-01-25,s1,30000.000000,40000.000000,5.0,10000.0,4.000000e+07
4,s05-s10000m,"LINESTRING (540095.882 4742645.456, 539704.822...",POINT (535096.832 4742648.569),2019-01-25,s1,40000.000000,50000.000000,NaN,10000.0,4.000000e+07
...,...,...,...,...,...,...,...,...,...,...
68,s69-s10000m,"LINESTRING (652338.76 4697682.02, 652197.878 4...",POINT (647339.987 4697611.472),2019-03-05,s4,274105.324868,284105.324868,NaN,10000.0,4.000000e+07
69,s70-s10000m,"LINESTRING (642341.15 4697526.723, 641994.147 ...",POINT (637342.194 4697445.552),2019-03-05,s4,284105.324868,294105.324868,NaN,10000.0,4.000000e+07
70,s71-s10000m,"LINESTRING (632343.125 4697349.07, 632326.134 ...",POINT (627344.065 4697254.461),2019-03-05,s4,294105.324868,304105.324868,NaN,10000.0,4.000000e+07
71,s72-s10000m,"LINESTRING (622345.629 4697147.973, 622000.67 ...",POINT (617346.364 4697062.225),2019-03-05,s4,304105.324868,314105.324868,2.0,10000.0,4.000000e+07
72,s73-s10000m,"LINESTRING (612347.04 4696980.054, 612333.116 ...",POINT (607348.392 4696882.591),2019-03-05,s4,314105.324868,324105.324868,4.0,10000.0,4.000000e+07

### Modify a ```Samples``` object
Before we save our ```Samples``` object, there are a few things that we might want to modify.

#### Reproject
We can reproject our ```Samples``` object to a CRS of our choosing with the ```Samples.reproject()``` method which takes a single argument: the target CRS.
<br>In our example below, we reproject our ```Samples``` object to EPSG:4326 and then print it to see that the ```line``` and ```midpoint``` columns are now in lat-lon coordinates.

In [27]:
u_samples.reproject(crs_target='EPSG:4326')
u_samples.samples

Success: additional geometry column "midpoint" reprojected to CRS "EPSG:4326"
Success: reprojected to CRS "EPSG:4326"

,segment_id,line,midpoint,date,section_id,dfbsec_beg,dfbsec_end,individuals,se_length,se_area
0,s01-s10000m,"LINESTRING (-68.02 42.83433, -68.02117 42.8343...",POINT (-68.08117 42.8345),2019-01-25,s1,0.000000,10000.000000,1.0,10000.0,4.000000e+07
1,s02-s10000m,"LINESTRING (-68.14233 42.83483, -68.1445 42.83...",POINT (-68.2035 42.835),2019-01-25,s1,10000.000000,20000.000000,NaN,10000.0,4.000000e+07
2,s03-s10000m,"LINESTRING (-68.26468 42.83517, -68.2675 42.83...",POINT (-68.32585 42.83533),2019-01-25,s1,20000.000000,30000.000000,2.0,10000.0,4.000000e+07
3,s04-s10000m,"LINESTRING (-68.38703 42.83533, -68.39017 42.8...",POINT (-68.44821 42.83533),2019-01-25,s1,30000.000000,40000.000000,5.0,10000.0,4.000000e+07
4,s05-s10000m,"LINESTRING (-68.50938 42.83533, -68.51417 42.8...",POINT (-68.57055 42.8356),2019-01-25,s1,40000.000000,50000.000000,NaN,10000.0,4.000000e+07
...,...,...,...,...,...,...,...,...,...,...
68,s69-s10000m,"LINESTRING (-67.14846 42.4165, -67.15017 42.41...",POINT (-67.2092 42.41683),2019-03-05,s4,274105.324868,284105.324868,NaN,10000.0,4.000000e+07
69,s70-s10000m,"LINESTRING (-67.26995 42.417, -67.27417 42.417...",POINT (-67.3307 42.41717),2019-03-05,s4,284105.324868,294105.324868,NaN,10000.0,4.000000e+07
70,s71-s10000m,"LINESTRING (-67.39146 42.41717, -67.39167 42.4...",POINT (-67.45222 42.41715),2019-03-05,s4,294105.324868,304105.324868,NaN,10000.0,4.000000e+07
71,s72-s10000m,"LINESTRING (-67.51298 42.417, -67.51717 42.417...",POINT (-67.57374 42.417),2019-03-05,s4,304105.324868,314105.324868,2.0,10000.0,4.000000e+07
72,s73-s10000m,"LINESTRING (-67.6345 42.417, -67.63467 42.417,...",POINT (-67.69526 42.41683),2019-03-05,s4,314105.324868,324105.324868,4.0,10000.0,4.000000e+07

#### Extract coordinates
The coordinates of the ```midpoint``` column are now in lat-lon but they are still in a ```shapely.geometry``` which may complicate things later, if we want to, for example, get values for environmental variables from a satellite dataset at the coordinates of each centroid. So, we can use the ```Samples.coords()``` method to make two new columns: ```midpoint_lat``` and ```midpoint_lon```.
<br>We then print the samples to see these new columns.

In [28]:
u_samples.coords()
u_samples.samples

,segment_id,line,midpoint,midpoint_lon,midpoint_lat,date,section_id,dfbsec_beg,dfbsec_end,individuals,se_length,se_area
0,s01-s10000m,"LINESTRING (-68.02 42.83433, -68.02117 42.8343...",POINT (-68.08117 42.8345),-68.081169,42.834500,2019-01-25,s1,0.000000,10000.000000,1.0,10000.0,4.000000e+07
1,s02-s10000m,"LINESTRING (-68.14233 42.83483, -68.1445 42.83...",POINT (-68.2035 42.835),-68.203503,42.835000,2019-01-25,s1,10000.000000,20000.000000,NaN,10000.0,4.000000e+07
2,s03-s10000m,"LINESTRING (-68.26468 42.83517, -68.2675 42.83...",POINT (-68.32585 42.83533),-68.325849,42.835330,2019-01-25,s1,20000.000000,30000.000000,2.0,10000.0,4.000000e+07
3,s04-s10000m,"LINESTRING (-68.38703 42.83533, -68.39017 42.8...",POINT (-68.44821 42.83533),-68.448206,42.835330,2019-01-25,s1,30000.000000,40000.000000,5.0,10000.0,4.000000e+07
4,s05-s10000m,"LINESTRING (-68.50938 42.83533, -68.51417 42.8...",POINT (-68.57055 42.8356),-68.570552,42.835604,2019-01-25,s1,40000.000000,50000.000000,NaN,10000.0,4.000000e+07
...,...,...,...,...,...,...,...,...,...,...,...,...
68,s69-s10000m,"LINESTRING (-67.14846 42.4165, -67.15017 42.41...",POINT (-67.2092 42.41683),-67.209202,42.416830,2019-03-05,s4,274105.324868,284105.324868,NaN,10000.0,4.000000e+07
69,s70-s10000m,"LINESTRING (-67.26995 42.417, -67.27417 42.417...",POINT (-67.3307 42.41717),-67.330705,42.417170,2019-03-05,s4,284105.324868,294105.324868,NaN,10000.0,4.000000e+07
70,s71-s10000m,"LINESTRING (-67.39146 42.41717, -67.39167 42.4...",POINT (-67.45222 42.41715),-67.452223,42.417155,2019-03-05,s4,294105.324868,304105.324868,NaN,10000.0,4.000000e+07
71,s72-s10000m,"LINESTRING (-67.51298 42.417, -67.51717 42.417...",POINT (-67.57374 42.417),-67.573739,42.417000,2019-03-05,s4,304105.324868,314105.324868,2.0,10000.0,4.000000e+07
72,s73-s10000m,"LINESTRING (-67.6345 42.417, -67.63467 42.417,...",POINT (-67.69526 42.41683),-67.695258,42.416830,2019-03-05,s4,314105.324868,324105.324868,4.0,10000.0,4.000000e+07

### Save a ```Samples``` object
```Samples``` objects have an inbuilt ```save``` method to save the samples as a CSV or GPKG. The name of the saved file will be the name of the ```Samples``` object.

In [29]:
print(f'The saved file will be called \'{u_samples.name}.csv\'')
u_samples.save(
    folder=export_folder,
    filetype='gpkg'
)

The saved file will be called 'samples-sightings+effort-x-segments-s10000m.csv'

## Samples - point approach

### Make a ```Samples``` object...
If using the point approach, we can make a ```Samples``` object with the ```Samples.point()``` class method.

#### ...from a ```DataPoints``` object

In [30]:
u_samples = Samples.point(
    presences=u_presences,
    absences=u_absences,
    datapoints_p=u_sightings,
    cols_p=['individuals'])

### Access a ```Samples``` object's attributes
A ```Samples``` object, regardless of how it was made, will have three attributes (```name```, ```parameters```, and ```samples```) that we can access as follows.

In [31]:
u_samples.name

'samples-presences-sightings-+-absences-as-10000m-5day'

In [32]:
u_samples.parameters

{'approach': 'point',
 'resampled': 'datapoints',
 'presences_name': 'presences-sightings',
 'presences_crs': 'EPSG:32619',
 'absences_name': 'absences-as-10000m-5day',
 'absences_var': 'along',
 'absences_target': 20,
 'presencezones_crs': 'EPSG:32619',
 'presencezones_sp_threshold': 10000,
 'presencezones_tm_threshold': 5,
 'presencezones_tm_unit': 'day'}

In [33]:
u_samples.samples

,point_id,point,date,datapoint_id,p-a,individuals,section_id,dfbs
0,p01,POINT (579166.78 4742872.701),2019-01-25,d01,1,1.0,NaN,NaN
1,p02,POINT (554184.217 4742741.886),2019-01-25,d02,1,2.0,NaN,NaN
2,p03,POINT (548599.876 4742700.214),2019-01-25,d03,1,5.0,NaN,NaN
3,p04,POINT (520909.741 4714855.058),2019-03-02,d04,1,1.0,NaN,NaN
4,p05,POINT (532548.249 4714899.835),2019-03-02,d05,1,2.0,NaN,NaN
5,p06,POINT (512817.407 4705582.465),2019-03-02,d06,1,1.0,NaN,NaN
6,p07,POINT (504710.41 4705553.392),2019-03-02,d07,1,3.0,NaN,NaN
7,p08,POINT (654449.136 4716189.584),2019-03-05,d08,1,5.0,NaN,NaN
8,p09,POINT (645666.237 4716110.937),2019-03-05,d09,1,2.0,NaN,NaN
9,p10,POINT (643532.681 4716066.52),2019-03-05,d10,1,1.0,NaN,NaN
10,p11,POINT (629124.489 4706545.106),2019-03-05,d11,1,3.0,NaN,NaN
11,p12,POINT (620560.818 4697116.949),2019-03-05,d12,1,2.0,NaN,NaN
12,p13,POINT (611976.857 4696974.111),2019-03-05,d13,1,4.0,NaN,NaN
13,a01,POINT (507756.09 4742533.885),2019-01-25,NaN,0,NaN,s1,72343.302935
14,a02,POINT (572007.936 4733595.246),2019-01-30,NaN,0,NaN,s2,100928.529720
15,a03,POINT (567397.331 4733567.597),2019-01-30,NaN,0,NaN,s2,105539.543489
16,a04,POINT (564150.274 4733554.443),2019-01-30,NaN,0,NaN,s2,108786.939491
17,a05,POINT (562757.916 4733541.649),2019-01-30,NaN,0,NaN,s2,110179.356421
18,a06,POINT (565802.173 4715098.573),2019-03-02,NaN,0,NaN,s3,238013.826962
19,a07,POINT (579797.698 4715159.618),2019-03-02,NaN,0,NaN,s3,252011.997403
20,a08,POINT (553817.644 4705797.399),2019-03-02,NaN,0,NaN,s3,321359.855533
21,a09,POINT (544923.102 4705771.016),2019-03-02,NaN,0,NaN,s3,330255.261038
22,a10,POINT (536940.771 4705708.782),2019-03-02,NaN,0,NaN,s3,338238.164285
23,a11,POINT (656664.334 4743965.846),2019-03-05,NaN,0,NaN,s4,382172.024217
24,a12,POINT (656675.235 4743486.754),2019-03-05,NaN,0,NaN,s4,382651.239332
25,a13,POINT (656727.916 4741170.761),2019-03-05,NaN,0,NaN,s4,384967.831525
26,a14,POINT (636018.631 4734429.329),2019-03-05,NaN,0,NaN,s4,411848.260024
27,a15,POINT (621812.769 4734182.859),2019-03-05,NaN,0,NaN,s4,426058.797724
28,a16,POINT (612022.804 4724737.877),2019-03-05,NaN,0,NaN,s4,463936.909800
29,a17,POINT (630498.436 4725084.925),2019-03-05,NaN,0,NaN,s4,482416.283494
30,a18,POINT (637794.804 4725226.246),2019-03-05,NaN,0,NaN,s4,489714.020642
31,a19,POINT (619609.48 4715631.158),2019-03-05,NaN,0,NaN,s4,555356.510491
32,a20,POINT (655249.075 4697683.58),2019-03-05,NaN,0,NaN,s4,646115.454939

### Modify a ```Samples``` object
Before we save our ```Samples``` object, there are a few things that we might want to modify.

#### Thin
We can thin our ```Samples``` object with the ```Samples.thin``` method.

In [34]:
u_samples.thin(
    coords='point',
    sp_threshold=10000)

#### Reproject
We can reproject our ```Samples``` object to a CRS of our choosing with the ```Samples.reproject()``` method which takes a single argument: the target CRS.
<br>In our example below, we reproject our ```Samples``` object to EPSG:4326 and then print it to see that the ```point``` column is now in lat-lon coordinates.

In [35]:
u_samples.reproject(crs_target='EPSG:4326')
u_samples.samples

Success: reprojected to CRS "EPSG:4326"

,point_id,point,date,datapoint_id,p-a,individuals,section_id,dfbs
0,p01,POINT (-68.03133 42.83433),2019-01-25,d01,1,1.0,NaN,NaN
1,p02,POINT (-68.337 42.83533),2019-01-25,d02,1,2.0,NaN,NaN
2,p04,POINT (-68.74517 42.58583),2019-03-02,d04,1,1.0,NaN,NaN
3,p05,POINT (-68.60333 42.58583),2019-03-02,d05,1,2.0,NaN,NaN
4,p07,POINT (-68.94267 42.50233),2019-03-02,d07,1,3.0,NaN,NaN
5,p08,POINT (-67.11783 42.58267),2019-03-05,d08,1,5.0,NaN,NaN
6,p10,POINT (-67.25083 42.58367),2019-03-05,d10,1,1.0,NaN,NaN
7,p11,POINT (-67.4285 42.5005),2019-03-05,d11,1,3.0,NaN,NaN
8,p12,POINT (-67.53467 42.417),2019-03-05,d12,1,2.0,NaN,NaN
9,a01,POINT (-68.9051 42.83534),2019-01-25,NaN,0,NaN,s1,72343.302935
10,a02,POINT (-68.1201 42.7515),2019-01-30,NaN,0,NaN,s2,100928.529720
11,a06,POINT (-68.19807 42.5855),2019-03-02,NaN,0,NaN,s3,238013.826962
12,a07,POINT (-68.02751 42.58473),2019-03-02,NaN,0,NaN,s3,252011.997403
13,a08,POINT (-68.34499 42.50267),2019-03-02,NaN,0,NaN,s3,321359.855533
14,a10,POINT (-68.55039 42.50286),2019-03-02,NaN,0,NaN,s3,338238.164285
15,a12,POINT (-67.08317 42.82791),2019-03-05,NaN,0,NaN,s4,382651.239332
16,a14,POINT (-67.33796 42.75033),2019-03-05,NaN,0,NaN,s4,411848.260024
17,a15,POINT (-67.51154 42.7505),2019-03-05,NaN,0,NaN,s4,426058.797724
18,a16,POINT (-67.633 42.66696),2019-03-05,NaN,0,NaN,s4,463936.909800
19,a17,POINT (-67.40754 42.66717),2019-03-05,NaN,0,NaN,s4,482416.283494
20,a19,POINT (-67.54236 42.58383),2019-03-05,NaN,0,NaN,s4,555356.510491
21,a20,POINT (-67.1131 42.41594),2019-03-05,NaN,0,NaN,s4,646115.454939

#### Extract coordinates
The coordinates of the ```point``` column are now in lat-lon but they are still in a ```shapely.geometry``` which may complicate things later, if we want to, for example, get values for environmental variables from a satellite dataset at the coordinates of each centroid. So, we can use the ```Samples.coords()``` method to make two new columns: ```point_lat``` and ```point_lon```.
<br>We then print the samples to see these new columns.

In [36]:
u_samples.coords()
u_samples.samples

,point_id,point,point_lon,point_lat,date,datapoint_id,p-a,individuals,section_id,dfbs
0,p01,POINT (-68.03133 42.83433),-68.031330,42.834330,2019-01-25,d01,1,1.0,NaN,NaN
1,p02,POINT (-68.337 42.83533),-68.337000,42.835330,2019-01-25,d02,1,2.0,NaN,NaN
2,p04,POINT (-68.74517 42.58583),-68.745170,42.585830,2019-03-02,d04,1,1.0,NaN,NaN
3,p05,POINT (-68.60333 42.58583),-68.603330,42.585830,2019-03-02,d05,1,2.0,NaN,NaN
4,p07,POINT (-68.94267 42.50233),-68.942670,42.502330,2019-03-02,d07,1,3.0,NaN,NaN
5,p08,POINT (-67.11783 42.58267),-67.117830,42.582670,2019-03-05,d08,1,5.0,NaN,NaN
6,p10,POINT (-67.25083 42.58367),-67.250830,42.583670,2019-03-05,d10,1,1.0,NaN,NaN
7,p11,POINT (-67.4285 42.5005),-67.428500,42.500500,2019-03-05,d11,1,3.0,NaN,NaN
8,p12,POINT (-67.53467 42.417),-67.534670,42.417000,2019-03-05,d12,1,2.0,NaN,NaN
9,a01,POINT (-68.9051 42.83534),-68.905096,42.835337,2019-01-25,NaN,0,NaN,s1,72343.302935
10,a02,POINT (-68.1201 42.7515),-68.120098,42.751500,2019-01-30,NaN,0,NaN,s2,100928.529720
11,a06,POINT (-68.19807 42.5855),-68.198066,42.585500,2019-03-02,NaN,0,NaN,s3,238013.826962
12,a07,POINT (-68.02751 42.58473),-68.027515,42.584729,2019-03-02,NaN,0,NaN,s3,252011.997403
13,a08,POINT (-68.34499 42.50267),-68.344988,42.502670,2019-03-02,NaN,0,NaN,s3,321359.855533
14,a10,POINT (-68.55039 42.50286),-68.550394,42.502862,2019-03-02,NaN,0,NaN,s3,338238.164285
15,a12,POINT (-67.08317 42.82791),-67.083170,42.827910,2019-03-05,NaN,0,NaN,s4,382651.239332
16,a14,POINT (-67.33796 42.75033),-67.337963,42.750330,2019-03-05,NaN,0,NaN,s4,411848.260024
17,a15,POINT (-67.51154 42.7505),-67.511540,42.750498,2019-03-05,NaN,0,NaN,s4,426058.797724
18,a16,POINT (-67.633 42.66696),-67.632999,42.666958,2019-03-05,NaN,0,NaN,s4,463936.909800
19,a17,POINT (-67.40754 42.66717),-67.407542,42.667170,2019-03-05,NaN,0,NaN,s4,482416.283494
20,a19,POINT (-67.54236 42.58383),-67.542362,42.583830,2019-03-05,NaN,0,NaN,s4,555356.510491
21,a20,POINT (-67.1131 42.41594),-67.113103,42.415937,2019-03-05,NaN,0,NaN,s4,646115.454939

### Save a ```Samples``` object
```Samples``` objects have an inbuilt ```save``` method to save the samples as a CSV or GPKG. The name of the saved file will be the name of the ```Samples``` object.

In [37]:
print(f'The saved file will be called \'{u_samples.name}.csv\'')
u_samples.save(
    folder=export_folder,
    filetype='gpkg'
)

The saved file will be called 'samples-presences-sightings-+-absences-as-10000m-5day.csv'